//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj02N.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int CodCliente { get; set; }
        public int CodPedido { get; set; }
        public Nullable<System.DateTime> DataPedido { get; set; }
        public Nullable<decimal> Valor { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
